# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 18:52
from __future__ import unicode_literals

import apps.form_field
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', apps.form_field.FixedCharField(db_index=True, max_length=255)),
                ('last_name', apps.form_field.FixedCharField(db_index=True, max_length=255)),
                ('room', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
